@startuml
Гость -> (Просмотр списка товаров)
Гость -> (Регистрация)
(Просмотр списка товаров) <.. (Просмотр товара) : extends
(Просмотр списка товаров) <.. (Поиск и фильтрация) : extends

Гость <|... Пользователь
Пользователь -> (Покупка товара)
(Покупка товара) ..> (Добавление в корзину) : include
(Покупка товара) .> (Оплата) : include

Пользователь <|... Администратор
Администратор -> (Управление товарами)
(Управление товарами) <.. (Добавление товара)
(Управление товарами) <.. (Изменение товара)
(Управление товарами) <.. (Удаление товара)
Администратор --> (Управление категориями)
@enduml